### ISSUE TITLE
pfe-modal --theme in the content area does not work as expected

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1090]
Currently when a modal trigger is inside a dark theme, the broadcast colors are still set to the dark theme, so the CTA is the incorrect color:
![image](https://user-images.githubusercontent.com/456863/92670926-0eeafa80-f2e3-11ea-896c-c08b829cb063.png)

Setting the `--theme` custom property *should* do the trick, but it doesn't seem to work in this instance:

![image](https://user-images.githubusercontent.com/456863/92671048-52456900-f2e3-11ea-85e5-0c35c093e324.png)

So I added `@include pfe-set-broadcast-theme(light);` so that the links would be the correct color most of the time, because most modal content windows probably have a white background. Without `--theme` working as intended though, devs cannot set `--pfe-modal__window--BackgroundColor` to something dark or saturated.

**Comment by castastrophe** [comment]
> Setting the --theme custom property should do the trick, but it doesn't seem to work in this instance:

So here's the thing about context - it's for communicating from parent to child.  It's not great at communicating internal to a component.  I'm not even sure that's desirable.  Since modal is setting its own background color, we really don't need JavaScript to tell it how to style its content.  It should just intervene and update the broadcast values.

**Comment by starryeyez024** [comment]
Note to self, we should add inline links to the demo file (all examples).

**Comment by castastrophe** [comment]
This appears to have been corrected now
