### ISSUE TITLE
[tools] Release | Update to independent versioning

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1453]
## Description of the requested feature

- Update lerna release script to support independent versioning of components.

**Comment by castastrophe** [comment]
https://github.com/lerna/lerna#independent-mode

**Comment by mwcz** [comment]
Adding notes for myself and others who may not have looked at lerna versioning settings recently.

We're currently using the default, fixed/locked mode.  Contrary to its name, elements can still have their own version, and those versions are only bumped when the element changes<sup>1</sup>.

![Screenshot from 2021-07-28 14-56-04](https://user-images.githubusercontent.com/364615/127380177-0a102a7d-9c94-4210-9ba5-11aeb457dee6.png)

With independent mode, during each release we'll be asked to specify a new version number element.  

![Screenshot from 2021-07-28 14-56-12](https://user-images.githubusercontent.com/364615/127380716-87ee7cbc-0fbd-4732-85b9-bd717eecc54c.png)

<sup>1</sup> - Something appears to be preventing this from working.  My best guess is it's because of how we add and remove the elements' `dist` dirs during each release.  However, lerna.json has `dist` ignored, so it shouldn't be a problem.  Needs more investigation.

**Comment by bennypowers** [comment]
This is done in 2.0, and with changesets, yet
