### ISSUE TITLE
[fix] pfe-icon | When setting background color, variable --pfe-icon--color is being used for both that and the icon

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1541]
There are two instances of the color variable:
 - `--pfe-icon--color` used in the border and background property
 - `--pfe-icon--Color` used to color the icon itself

They do interfere with one another, like if the lowercase version is used, the uppercase version doesn't work.  Custom property names are supposed to be case sensitive, but if I change `--pfe-icon--color` to `--pfe-icon--foo` (everywhere) it seems to work as expected. 

![pfe-icon-color](https://user-images.githubusercontent.com/456863/114939108-f826fc00-9e0d-11eb-9f67-eec986237b37.gif)

**Comment by castastrophe** [comment]
`--pfe-icon--Color` - so this is actually incorrect.  `--pfe-icon--color` should be the only one used anywhere in the component.  `--pfe-icon--Color` is deprecated but still supported for backwards compatibility.

**Comment by castastrophe** [comment]
I believe the bug is that there is no way to customize the icon color is the background color is changed because --pfe-icon--color influences both right now

It's not an issue when you use attributes because those variables are empty.

Perhaps we can add a `--pfe-icon--BackgroundColor` for the circle specifically?

**Comment by starryeyez024** [comment]
Yeah I think that previously the `color` prop was lowercase because it was trying to influence two things, border and background color, but maybe we just remove that from the stack. So if you want to use vars to change colors, you just use whichever of the three you need:
`--pfe-icon--Color`
`--pfe-icon--BackgroundColor`
`--pfe-icon--BorderColor`

I think the fact that `--pfe-icon--color` still exists in the component is undesirable. We likely want only the three actual vars listed above, and then have `--pfe-icon--color: var(--pfe-icon--Color);` as the support for backwards compatibility

Beyond this, I'm getting some inconsistent results on  http://localhost:8000/elements/pfe-icon/demo/
It seems like some of the icons still have inline styles for color?

![image](https://user-images.githubusercontent.com/456863/115052439-f1e75d00-9eab-11eb-9d20-3300a2d40a62.png)

**Comment by castastrophe** [comment]
@starryeyez024 You've got it backwards though.  There is not `--pfe-icon--Color` because this is an SVG not typography so you can't style using `color: foo`.  We're letting users set the concept of the icon color which is lowercase: `--pfe-icon--color`.  The only reason `--pfe-icon--Color` still exists at all is for backwards compatibility.

**Comment by castastrophe** [comment]
Cool with adding these: `--pfe-icon--BackgroundColor`, `--pfe-icon--BorderColor` as they're literally styling those properties but we either create a new variable called: `--pfe-icon--Fill` or we keep it as `--pfe-icon--color`.

**Comment by starryeyez024** [comment]
Ah yes, sorry, I meant `--pfe-icon--FloodColor` not just `Color`.
