### ISSUE TITLE
Documentation: theming concerns

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#163]
For non-RHElement themes like Bootstrap, we need to advise developers and themers to manage their own link colors. We noticed that link colors on saturated backgrounds can be hard to see based on the default blue link color provided by the browser, or theme, or Bootstrap, etc.

This looks pretty gross
<img width="1792" alt="screen shot 2018-09-14 at 11 15 27 am" src="https://user-images.githubusercontent.com/330256/45559078-83335600-b80f-11e8-9344-bde274a6f438.png">

We need to advise developers to include styles like this to make the links look better.

```
[color="dark"] a,
[color="darkest"] a,
[color="complement"] a,
[color="accent"] a {
    color: white;
    text-decoration: underline;
}
```

This looks better using the above styles.
<img width="1792" alt="screen shot 2018-09-14 at 11 18 19 am" src="https://user-images.githubusercontent.com/330256/45559233-eb823780-b80f-11e8-93c0-0ae8cee3c029.png">

In RHElement based themes, the color contrast issues will be handled by this code in the theme.
```
a {
    color: var(--rh-broadcasted--color--ui-link);
}

a:visited {
    color: var(--rh-broadcasted--color--ui-link--visited);
}

a:hover {
    color: var(--rh-broadcasted--color--ui-link--hover);
}

a:focus {
    color: var(--rh-broadcasted--color--ui-link--focus);
}
```

**Comment by starryeyez024** [comment]
This is also a really good reason for having a generic component that people can drop in, and it comes equipped with "nice" styles for basic HTML tags.
```
<rh-card>
  <rh-generic slot="content">
    <h2>Hello I'm using Overpass and i'm all brand-standards-like</h2>
    <p>Me too! no extra styles required here.</p>
  </rh-generic>
</rh-card>
```

**Comment by markcaron** [comment]
@starryeyez024, as we talked about today, the need for handling CSS in this way is because the elements in the `<slot>` are styled on their way in, and cannot be influenced by the component's ShadowDOM CSS (or ShadyCSS)—except for the first-child to my knowledge [1].

So the options are...

1) the consumer developer will have to add CSS like:

```
a {
    color: var(--rh-broadcasted--color--ui-link);
}
```

2) the consumer dev will have to use some sort of "generic" content component (I prefer `rh-content`) to append this type of generic element CSS to the `<head>` on the fly.

3) the consumer dev will have a RH Elements theme already handling these generic elements styles.

All of these are opt-in. But, if the consumer dev doesn't do any of these, then the content in the `<slot>` is added at their own risk  (i.e. potentially clashing contrast, styles, etc.).

Also, my [new PR](https://github.com/RHElements/rhelements/pull/184), at your request, should also allow devs to target/scope these generic CSS styles too.

Notes:
[1] I would _love_ to be proven wrong!

**Comment by markcaron** [comment]
@KrystalMoore16, we need to add this to our documentation.
