### ISSUE TITLE
[docs] Double-check updates to all component docs

### ISSUE THREAD

**Issue by markcaron** [patternfly/patternfly-elements#2395]
Need a once over on all docs to make sure they're accurate, have demos linked, and are ready to go.

**Comment by kylebuch8** [comment]
I don't think we want to link to the demo pages. Those are intended for the developers to review every possible use case of the component. I think we want to have multiple examples on the docs page and keep the demo page unlinked.

**Comment by zeroedin** [comment]
@kylebuch8  So currently we only show the demo link overlay when **NOT** in prod.  

https://github.com/patternfly/patternfly-elements/blob/a57ce830de318a0067f581537d42d1844f5abe97/docs/components/index.html#L24-L33

Otherwise, I think we can close this issue as I think this was covered in: https://github.com/patternfly/patternfly-elements/pull/2398
