### ISSUE TITLE
@cpelements/pfe-navigation@1.0.118: invalid media query

### ISSUE THREAD

**Issue by sumitridhal** [patternfly/patternfly-elements#2474]
Description:
The pfe-navigation–lightdom.css file in @cpelements/pfe-navigation@1.0.118 contains an invalid media query at lines 832, 2020, and 2435. The media query is missing the required value for min-width, resulting in a syntax error. The invalid media query is @media (min-width: ) {.

Steps to Reproduce:

Install @cpelements/pfe-navigation@1.0.118
Inspect the pfe-navigation–lightdom.css file
Look for media queries at lines 832, 2020, and 2435
Expected Result:
Valid media queries that contain the required value for min-width.

Actual Result:
Invalid media query @media (min-width: ) { without the required value for min-width.

Screenshots/Code Snippets:

scss
```
@media (min-width: ) {
  /* invalid media query */
}
```

<img width="810" alt="image" src="https://user-images.githubusercontent.com/2717960/231127823-fdad16bf-2b72-439c-aa55-c7d2e33d36d6.png">

Possible Solution:
Update the media queries at lines 832, 2020, and 2435 to include a value for min-width.

Additional Information:
None.

**Comment by wesruv** [comment]
To confuse everyone (and for reasons I never liked), this component is called **pfe**-navigation lives in the **cp**-elements repo.

Chris Hill copied this issue over to there: https://gitlab.cee.redhat.com/customer-platform/cp-elements/-/issues/3

This issue is resolved now, thanks for the bug report!
Latest on the nav is now: `@cpelements/pfe-navigation@1.0.119`

**Comment by bennypowers** [comment]
Please subscribe to https://github.com/RedHat-UX/red-hat-design-system/issues/375 for updates on the development of `<rh-navigation>`, which is supposed to supercede `<pfe-navigation>`
