### ISSUE TITLE
Add warning and error throwing to PFElement

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#357]
I think we should add a warn or message function to the PFElements root class to be used in components for throwing warnings and errors in a standard way.

See this example for PfeAccordion:
```
console.warn(`${PfeAccordionHeader.tag}: The first child in the light DOM must be a Header level tag (h1, h2, h3, h4, h5, or h6)`);
```

This will also allow us to add a flag to turn warnings on and off in the browser.  Warnings should only show in dev environments and not in production (+ documentation on how to set this up correctly for the different environments).  My vote would be default = warnings off, flag for dev = warnings on.  Errors always on.

**Comment by mwcz** [comment]
That's what I had in mind for the `log` function.  You can call `this.log("foo")` from within any element, and it will log to the console if the debugLog has been enabled.  That could be expnaded to include warnings pretty easily.

Errors are a little trickier to abstract into PFElement because the stack trace needs to be preserved.  If PFElement is the one throwing the error, it will look like the error came from `pfelement.js:84` for example.

**Comment by castastrophe** [comment]
I'm not sure when but this work seems to be complete.  I'll close out this issue but please reopen if a gap is found.
