### ISSUE TITLE
POC for including patternfly assets in static webpages

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-elements#661]
We'd like to know the impact of including PatternFly (and dependent assets) in static web pages, to better understand what kind of performance-related impacts it may have on overall site experience. Not just performance, but also to understand potential namespace conflicts one may run into. Let's create a simple POC that exercises loading PatternFly in a variety of ways, so we can determine what considerations we may need to take into account when using PatternFly core/react alongside an existing web site page.

**Comment by redallen** [comment]
I made a POC and left results in a different issue. Duplicate of https://github.com/patternfly/patternfly-webcomponents/issues/2 .

**Comment by kylebuch8** [comment]
# PatternFly 4 React on the Customer Portal: POC

This proof-of-concept is to evaluate what it takes to add a PatternFly 4 React component to the Customer Portal ([https://access.redhat.com](https://access.redhat.com)).

## The Environment

We used [spandx](https://www.npmjs.com/package/spandx), an npm package that we use for doing local development on pages and apps, to add the chroming (header, footer, CSS, and JS) from the Customer Portal. We also used [create-react-app](https://www.npmjs.com/package/create-react-app) to quickly scaffold a bare-bones react app. We then npm installed PatternFly 4 with React and added a PF4 React Accordion to the page.

![dev foo redhat com_1337_react-test___1_](https://user-images.githubusercontent.com/330256/73545856-318e6a00-440a-11ea-9e88-8731583af72f.png)

Zack Allen also [added a PatternFly 4 React Accordion component to the homepage of the Customer Portal](https://github.com/patternfly/patternfly-webcomponents/issues/2#issuecomment-575221170).

![pasted image 0](https://user-images.githubusercontent.com/330256/73546020-774b3280-440a-11ea-94ff-6210dd887a9b.png)

## End Result

### Performance Impact

Adding the CSS and JS to the page added 88 KB (gzipped) to our payload just to add an accordion to the page. We’re sure we could optimize this further if we used Preact instead of React. The performance of Zack’s proof-of-concept wasn’t any better than the Customer Portal attempt, but it could be extended to perform better and in more use cases.

This is a screenshot of the file size that Zack was working with.

![pasted image 0 (1)](https://user-images.githubusercontent.com/330256/73546106-9fd32c80-440a-11ea-8bc5-d0e2193498ee.png)

I think the reason for the large bundle sizes here is that they weren’t gzipped like they were in Michael’s example.

If multiple instances of PatternFly 4 React components we used on a page, we’d need to render multiple “mini” React apps on the page for the display of each component. Each of these mini React apps would likely be dependent on a different version of React.  In cases where the entire page is a React app, the problem of needing mini apps goes away, but the problem arises of components depending on conflicting versions of React.

### SEO Impact

Both proof-of-concepts would not be SEO friendly since the markup for the content is dynamically added to the page. We can’t use light DOM with the PF4 React approach so all search engines, with the exception of Google, wouldn’t render the content of the page since they don’t execute JavaScript.

### If JS doesn’t execute or is disabled

![Screenshot from 2020-01-23 11-41-01](https://user-images.githubusercontent.com/330256/73546182-c2fddc00-440a-11ea-9351-54b7b03d3d3d.png)

We are currently looking into a service like [prerender.io](https://prerender.io/) that will allow us to route search crawlers to pre-rendered version of the page.

## PatternFly Element Comparison

If we were to add a PatternFly Element (web component) accordion to the homepage of the Customer Portal, the payload size is ~10 KB. The only CSS that is being added to the page is a 950 B file that helps hide the flash of unstyled content (FOUC) on pages that are not using a framework. We don’t have this same issue in applications using React, Vue, Angular, Polymer, etc.

### Script type=”module” Version: ~10 KB

#### Breakdown

- JS: 9 KB
- CSS: 950 B

![pasted image 0 (2)](https://user-images.githubusercontent.com/330256/73546319-0b1cfe80-440b-11ea-84b1-c836f737c0b7.png)

### UMD Version: ~13.2 KB

#### Breakdown

- JS: 12.3 KB
- CSS: 950 B

![pasted image 0 (3)](https://user-images.githubusercontent.com/330256/73546410-2f78db00-440b-11ea-8d99-87a9b2afc139.png)

### If JS doesn’t execute or is disabled

This is the case for all search engines except Google. In the case of the web component, we still get legible content with semantic value.

![pasted image 0 (4)](https://user-images.githubusercontent.com/330256/73546466-47e8f580-440b-11ea-8666-77d8d109ae84.png)
