### ISSUE TITLE
pfe-navigation dropdown has scrollbar

### ISSUE THREAD

**Issue by ryanissamson** [patternfly/patternfly-elements#703]
Passing along feedback I received which may or may not be able to be addressed. You'll notice in the right of the dropdown, there's a scrollbar even though the menu doesn't expand vertically enough to need it.

Chrome Version 79.0.3945.79

![image](https://user-images.githubusercontent.com/3143277/73371193-51dfec80-4283-11ea-864a-e36bdd857796.png)
![image-1](https://user-images.githubusercontent.com/3143277/73371734-20b3ec00-4284-11ea-8b16-e0bf3a03938b.png)

**Comment by starryeyez024** [comment]
Thanks for reporting, but this works as intended. If the contents of the tray is taller than the window, then the user needs a way to access that content, thus a scrollbar.

The scrollbar is forced as visible because if some trays may be taller than others, thus some would have scrollbars and others would not. The contents of the tray would "jump" in terms of horizontal alignment as you open various nav items. Watch the top left corner of the tray:

![menu tray jump](https://user-images.githubusercontent.com/456863/73875010-7fe4a400-4822-11ea-841c-58fd585bf6a5.gif)
