### ISSUE TITLE
[feat] pfe-navigation 1.x | ability to remove heading tags in pfe-navigation without visual changes

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#773]
currently if you change it to a `<p>` tag, the line height is messed up such that the text is nearly touching the icon. Login shows an `h3`, websites shows a `p` tag.

![image](https://user-images.githubusercontent.com/456863/75922238-9f2a1d80-5e30-11ea-8a8c-479365e47324.png)

(We need to remove headings for SEO reasons). Notice that "websites" is the last menu item, and it appears that all other content is nested under that: https://gsnedders.html5.org/outliner/process.py?url=https%3A%2F%2Fredhat.com

**Comment by castastrophe** [comment]
I'd be interested to learn more about the SEO reasons. This markup was recommended for the best accessible experience so removing headings will reduce usability of the nav by screen readers.

**Comment by markcaron** [comment]
All navigation, especially when marked up as a list (as it should be), **must** have a heading. We should also reference the heading through an `aria-labelledby` attribute on the list and an ID on the heading. This is the best practice.

SEO should automatically benefit from any accessibility measures. It is not often (if ever) where SEO "reasons" differ from best practices in Web Standards and accessibility.

**Comment by starryeyez024** [comment]
Jairus Mitchel, our SEO lead for redhat.com, recommended that we remove headers from the nav. 

In doing some research, I found some SEO tools which turn a website into an outline format by virtue of headings. In these, I noticed that it seems that much of our content is nested under "Websites", the last heading in the menu.
- https://gsnedders.html5.org/outliner/process.py?url=https%3A%2F%2Fredhat.com
- https://cloud.magiclen.org/us/html-outliner

In searching for accessible examples of menus, including mega menus, I noticed that nearly all do not include heading tags:
- https://adrianroselli.com/2019/06/link-disclosure-widget-navigation.html
- https://www.w3.org/WAI/GL/wiki/Using_HTML5_nav_element
- https://www.w3.org/WAI/tutorials/menus/structure/
- https://adobe-accessibility.github.io/Accessible-Mega-Menu/
- https://terrillthompson.com/tests/menus/accessible-mega-menu/test.html
- https://www.levelaccess.com/challenges-mega-menus-standard-menus-make-accessible/

Can you provide examples of where you've seen documentation insisting on headings within the nav? Thanks!

**Comment by starryeyez024** [comment]
Regardless, the pfe-nav styles should not change when the light DOM tags are changed from heading tags to paragraph tags.

**Comment by starryeyez024** [comment]
Update on this; this issue only seems to occur when the theme is applied, so we may have to make adjustments there (only, or in addition).

**Comment by starryeyez024** [comment]
PR: https://github.com/patternfly/patternfly-elements/pull/790

**Comment by wesruv** [comment]
I'm with @markcaron, these should be heading tags. None of those mega-menu example links have titles _in_ the menu, they simply can't fathom a mega menu as mega as our mega menu :stuck_out_tongue_closed_eyes: 

I don't think we need to find an example of how headings are used in a mega menu to justify this, this boils down to the very common a11y rule - if it's text that is short and describes what is directly underneath like a title might, it's a heading. I don't think being inside of navigation provides any caveat.

I'd also agree with @markcaron that any SEO advice that disagrees with a heading in a navigation element has to prove it; I don't buy that.

* it's better semantic HTML
* `<nav>` allows all phrasing content including <h1> - <h6>
* HTML5doctor.com has great examples of it copied from the specification: http://html5doctor.com/nav-element/

**Comment by wesruv** [comment]
Re: SEO thing, since no one has access to the inner-workings of search spiders, I'm guessing the 'no header in navigation' is coming from an article (I'd like to see it) or a tool, and if it's a tool I want to see the reasoning for why that's flagged.

Making that text not a header feels like removing a hand rail from a wheel chair ramp for feng shui.

**Comment by JairusMitchell** [comment]
My concerns are around  heading tags creating noise.
My recommendations are to keep H tags in page body content, ordered with the H1 at the top of the page, containing the focus of the page content, with H2s and H3s nested underneath.

My concerns are from Google's SEO Best Practice Starters guide (https://support.google.com/webmasters/answer/7451184?hl=en&ref_topic=9460495):

"Use heading tags to emphasize important text

Use meaningful headings to indicate important topics, and help create a hierarchical structure for your content, making it easier for users to navigate through your document.
Best Practices

Imagine you're writing an outline

Similar to writing an outline for a large paper, put some thought into what the main points and sub-points of the content on the page will be and decide where to use heading tags appropriately.

Avoid:

    Placing text in heading tags that wouldn't be helpful in defining the structure of the page.
    Using heading tags where other tags like <em> and <strong> may be more appropriate.
    Erratically moving from one heading tag size to another.

Use headings sparingly across the page

Use heading tags where it makes sense. Too many heading tags on a page can make it hard for users to scan the content and determine where one topic ends and another begins.

Avoid:

    Excessive use of heading tags on a page.
    Very long headings.
    Using heading tags only for styling text and not presenting structure."

**Comment by castastrophe** [comment]
This is the resource that provides a lot of our guidance around building navigation semantics that are accessible: https://www.w3.org/WAI/tutorials/menus/structure/

And more generally, this is some information around structuring pages semantically: https://www.w3.org/WAI/tutorials/page-structure/regions/

The tldr; here is that headings, when used in connection with appropriate aria labels and roles, can provide important information about the sets of navigational lists.  This is especially important because our navigation is so complex.  If you feel strongly about heading use for SEO, our workaround could be a system of aria labels but the mark-up will be much more complex to implement for developers which was why we went through route of h-tags + lists.

**Comment by wesruv** [comment]
I like @castastrophe's suggestion, I would add that it's a significant amount of work to documentation, plan, and implement an alternative to headlines though.

Re: https://support.google.com/webmasters/answer/7451184?hl=en&ref_topic=9460495
I think that content is targeted at smaller sites, hence 'Starter Guide', I don't think all of it's advice scales to enterprise corporate sites.

**I'd add in defense of the SEO-ness of the nav markup with headings:**
We have a very meaningful document structure, the `nav` is outside of `main`, so Google should know exactly what to do with our headings in the navigation and exactly where the page content is. We have gone out of our way to make that _extremely easy_.

I promise I'm not trying to pull a card here (:roll_eyes: at self), but trying to frame my confusion and viewpoint:
Since 2009 I've been building enterpise level sites and their navigations; there are at least 6 mega menus on high traffic sites that I was the lead on, and all were scrutinized by internal and/or vendor SEO teams. This hasn't come up before or after we've implemented as an issue.

A couple that are still up in some form that also have headlines in their nav:
* bravotv.com / oxygen.com (they are essentially the same codebase with a slightly different Drupal theme and CSS last I knew)
* syfy.com (I wasn't lead, but helped)
* AiChe.org
* Quest.com

**Comment by jpsherman** [comment]
I want to echo what @JairusMitchell said. John Mu (Google Trends Analyst @ Google) [had this exchange on Twitter](https://twitter.com/M_Sauermann/status/852105945245261824) saying pretty much that you _**can**_ use as many HI tags as you want. This implies that there's no penalty for using multiple H1 tags on a single page... BUT... 

There is such a thing as Heading spam. Greg Gifford an expert in the auto industry SEO verticlal goes over how he's seen [H1 tags be used incorrectly and presumably](https://www.dealeron.com/blog/stop-abusing-h1-headings/) to "add a bit of ooph to the keyword". 

So, there are bad ways to use multiple H1 tags that look like spam and you can also use many H1 tags without getting hit by a Google penalty. 

As Jairus noted, "Use heading tags to emphasize important text". This is about efficiency and clarity. Multiple H1 tags is like "bolding" the entire block of text, the intent of the bold format is to emphasize something that's important. All the content being "bold" means that nothing stands out because everything is important. 

Multiple H1's don't clarify, they don't emphasise and they add noise. Google is clever, but it doesn't want or need to parse through multiple H1s to try to figure out what's doubleplus important based on the H1. I think of header tags as salt.... too much ruins it, but just enough makes it better. 

(a very long winded way of saying Jairus is right)

**Comment by jpsherman** [comment]
got more context from @wesruv - digging a bit deeper.

**Comment by wesruv** [comment]
Danke sir. I'm definitely not a fan of the h1's everywhere approach to post HTML5 semantic markup.

I'm open to removing headings from nav; I just want more info to understand this since it can cause a11y issues, and to fix that it causes some harder to maintain code.

**Comment by starryeyez024** [comment]
Just to throw in some specifics to illustrate the point, I want to note a couple things that are true of redhat.com's navigation:

 - Since the sets of unordered lists are nested, some of the items are already structured. If you are a site visitor viewing or listening to the `Products` menu item, then you have already heard or seen the word "Products" in order to have chosen to select that item and view its children. So the relationship there is obvious.
- However, the groups of items within the tray do not include enough semantic markup to provide meaning for visitors using screen-readers. For example the word "Platforms" is intended to be a heading over the items RHEL, Jboss, OpenStack, & RHV. But currently it has only a div + span tag wrapper. Only through styles are we communicating to sighted users that's what the word "Platforms" means. 

Would it be an acceptable compromise if we avoid using heading tags, but instead apply aria labels such as `userole="heading" aria-level="2"`?

I found a few examples of complex mega menus that are still adhering to accessibility best practices. Some with heading tags, some without.  One of these is from the company we are actually pursuing consulting help from, around accessibility. :) 
 - https://www.levelaccess.com/challenges-mega-menus-standard-menus-make-accessible/
 - https://dequeuniversity.com/library/aria/menus/megamenu

**Comment by starryeyez024** [comment]
Also worth nothing, the issue was originally opened around the utility items, which are not in unordered lists nor do they have heading tags, so we'd want to put ARIA roles on those too.

**Comment by wesruv** [comment]
I think it's something we should support in PFE Nav, but I don't want to make it the norm.

I'd like to make it so the heading styling doesn't show up unless it's a heading tag, or there's the appropriate aria attributes to make it a heading.

I have a ticket to document this under 'advanced' use cases for the unified nav.

**Comment by bennypowers** [comment]
This issue should be moved to RHDS when it's established

**Comment by wesruv** [comment]
This is resolved in the nav, I'm going to close this.
