### ISSUE TITLE
DOC | JSdoc auto-documentation

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#89]
Set up jsdoc (probably) documentation.

**Comment by castastrophe** [comment]
Guide: https://github.com/jsdoc/jsdoc
Gulp: https://github.com/deshaw/gulp-jsdoc3

**Comment by starryeyez024** [comment]
Hey folks, can y'all elaborate (1 or 2 bullet points) about why this is needed, how it's awesome, etc. Thanks!

**Comment by castastrophe** [comment]
The JSDoc plugin will provide an in-code way to document public-facing API in components and all the available methods for PFElement.  This can reduce duplication and improve understanding of what the base class brings to the table.

**Comment by heyMP** [comment]
👍   

It can also improve the developer experience since VSCode can use JSDoc comments to populate its autocomplete, similar to typescript.
https://dev.to/henryjw/better-javascript-type-autocomplete-with-jsdoc-3bdo

And we could convert JSdoc to markdown to potentially auto generate docs.
https://dev.to/henryjw/better-javascript-type-autocomplete-with-jsdoc-3bdo
