### ISSUE TITLE
Jump links nav height in CSS variable is incorrect

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#904]
The variable seems to be smaller than the actual size of the jump-links-nav, and it also doesn't accurately reflect the state of the nav, whether its open or closed, in all browsers. We probably need an event to fire when it opens or closes, which triggers the reportHeight function to fire again.

### *Open or Closed*

The CSS variable says its 37px:

![image](https://user-images.githubusercontent.com/456863/83645698-c653d080-a580-11ea-9f2c-5ca0f81bf239.png)

but its actually 62.4px:

![image](https://user-images.githubusercontent.com/456863/83646970-57777700-a582-11ea-8b28-9e89e4f977f7.png)

### *Open*

variable 297px:
![image](https://user-images.githubusercontent.com/456863/83646541-c30d1480-a581-11ea-8950-4ae2bb068178.png)

actual height of pfe-jump-links-nav: 299px
![image](https://user-images.githubusercontent.com/456863/83646388-91944900-a581-11ea-8da9-fbe5a34bb2a2.png)

### *Closed*

variable: 36px or 37px
![image](https://user-images.githubusercontent.com/456863/83646460-a96bcd00-a581-11ea-8229-60cf108c3197.png)

actual height of pfe-jump-links-nav: 62px
![image](https://user-images.githubusercontent.com/456863/83646641-efc12c00-a581-11ea-87d3-dd9117541fc3.png)

**Comment by Djfaucette** [comment]
So all of the issues where we're 1-2px off is because we're using `.clientHeight` which doesn't factor in borders, scrollbars, margin, etc. I'm just using the method as implemented on pfe-navigation. I assumed there was a reason we're using that as opposed to some other methods. Easy fix.

The others I'm not sure. Maybe it's a race condition where the component hasn't calculated new height yet, or an expanded sub section closes/opens after it writes the rule.

**Comment by starryeyez024** [comment]
closing in favor of https://github.com/patternfly/patternfly-elements/issues/1017
