### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#92]
(Kind of a note-to-self)

Maybe we need a web component `rh-helper` with a set of shared functions to be used across components in the system.

Use cases:
- Containers will often have a background color associated with it and passed in as input; to enforce standardization in this area, we could have a function in this helper library that sets the background property/variable in a standardized way and is invoked in the container component by importing `rh-helper` and invoking `setBackground(value);`
- We have a need for the band layout to accept a custom hex value for the background color which means either the user has to set the theme or we need to interpolate the theme based on the brightness and hue of the color provided.  Since we can access this value in the JS, we could interpolate the theme using a shared function in this helper library `determineTheme(background)`.

**Comment by castastrophe** [comment]
Re: discussion with Kendall - cc @starryeyez024

**Comment by starryeyez024** [comment]
@castastrophe  +1 !  I think it might be wise to lean on the same function to determine the theme for background="primary" or secondary too, since those vars can be reset by a dev later.  Use case: if originally the Red Hat palette sets the CSS variable for the theme:primary the color to #C00, that would invoke a dark theme.  Later, if a SPA dev sets the primary theme color to light yellow, the javascript should look up to the root to find the value of --rh-theme_primary and see that its yellow, run the color helper function and determine that theme="light". 

Ok here's some terrible fast pseudo code, to see if we are saying the same thing?

```
function determineTheme
    if background color = hex
       then run color function to determine theme
    if background color = primary, secondary, accent (etc)
      get value from [CSS variable] & use color function to determine theme   // how would we determine *which* css var per layout? just lean on namespacing?
    set var layout_theme = [dark, light, desaturated, etc]  // we'd also need rules for desaturated
```

A separate function for passing the theme from layout component to children content component:

```
function themeHandoff
    parent = document.querySelector('rh-card');  // would need to abstract away name of layout
    children = parent.children;
    if children name starts with `rh-` and  component_type=content
        then set content_theme = layout_theme
   // we also need to add something here that tells the function to *not* apply to children if they are inside another layout.. this seems like it would be difficult. i.e. we dont want band layouts handing off theme attributes to children inside of card. Or if we did, they'd need to be overwritten by card. 
```

so you end up with a theme attribute on both, which are both dynamically generated:
```
<rh-card  background="primary"  layout-theme="dark">
    <rh-article-teaser  theme="dark">
```

cc @mwcz @markcaron

**Comment by starryeyez024** [comment]
@kylebuch8 Notes from today's meeting. I wasn't sure if I should add these to the project board so I'm just capturing them here for now:

- These helper functions should live within the base RHElement 
- We may create a base Container RHElement and a base Content RHElement so that yeoman can create a better template that's closer to the thing you are creating.
- Helper functions include:
    1.  determineTheme Function
        - Looks at CSS var for background color, determines light, dark, etc. theme.
        - https://codepen.io/castastrophee/pen/QrVgpb
    2. themeHandoff Function
        - see pseudo code above

**Comment by starryeyez024** [comment]
@castastrophe I'm closing this out, based on our conversation about not having theme attributes, and just using css variables to pass through "theme" info.
