### ISSUE TITLE
Discussion for 1.0: `pfe-sass` Developer Experience Improvements

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#946]
Starting this ticket because I'm working on "Red Hat Design System Site℠" and using pfe-sass as a base and have questions/thoughts around how the Sass is organized and named, and if we're going to make any changes to that, 1.0 would be a good time.

I'm still figuring out pfe, so it's very possible I'm missing context or reasons why things should be done a certain way.

So here are two thoughts, and as I run across other things I'll add them as comments
1. All color vars go in one file, this way if a color var refers to another color var I can quickly do a find in the same file for that. I think it would help speed up the 'designer gave me color x, do I already have a var for that' search which has been frustrating for me so far.
2. Remove lighten/darken/etc functions from color vars and replace them with calculated values, because it's easier to search for, and simply 'lightening' or 'darkening' via Sass functions often creates washed out colors.
3. Use maps instead of long lists of longer named vars, which I find harder to read, and technically I hear maps are more performant than having more vars but I don't think our build is particularly slow on the Sass front.
4. Comment all Mixins and Functions with SassDoc style docblocks (there are many undocumented things)
5. I see a separate folder for map vars, put those variables in with other files by the use of the var. The files are small and separating them based on var type isn't very intuitive to me. I didn't know these existed until I started picking around
6. Convert extends into mixins since extends cannot be used in media queries and what we save on CSS parsing for having less rules is teensy weensy
7. Include `@see` documentation for variables/mixins/functions that are closely tied to a specific variables/mixins/functions, e.g. `pfe-breakpoint` alludes to named breakpoints but doesn't describe them or provide a pointer to the var.

**Comment by castastrophe** [comment]
So much great stuff in here!  Thanks for putting so much thought into this and writing it out so organized and clearly.  I'm really excited to dive into this feedback.  Would you want to set up a meeting and maybe walk us through some of your ideas in person?

**Comment by wesruv** [comment]
Sure thing!

**Comment by starryeyez024** [comment]
I can't make the meeting tomorrow, so I'm brain-dumping some thoughts. :) 

> All color vars go in one file, this way if a color var refers to another color var I can quickly do a find in the same file for that. I think it would help speed up the 'designer gave me color x, do I already have a var for that' search which has been frustrating for me so far.

Have you looked at the `/pfe-styles/_temp/pfe-colors.css` file? This is a handy reference.

> Remove lighten/darken/etc functions from color vars and replace them with calculated values, because it's easier to search for, and simply 'lightening' or 'darkening' via Sass functions often creates washed out colors.

+1 on this. I had a [pull request](https://github.com/patternfly/patternfly-elements/pull/884/files#diff-5ae7cc88f82fdb6a36e0b29daa0ff5fb) going where we actually drop nearly all the crayon colors from PFE, and refer exclusively to the sass vars // hex colors in Patternfly core. The only reason I closed it was because we have other refactor PRs open and I would need to re-roll it anyway. The troubling part is it will still be hard to find hex colors since they will live in the `node_modules/@patternfly/patternfly` folder. Should we include the list, commented out, in our partials?

> Use maps instead of long lists of longer named vars, which I find harder to read, and technically I hear maps are more performant than having more vars but I don't think our build is particularly slow on the Sass front.

Can you elaborate on this? We have maps-a-plenty. Where are we specifically missing them?

> Comment all Mixins and Functions with SassDoc style docblocks (there are many undocumented things)

afaik they all have comment blocks above each. Are there some specifically that need more elaborate comments? Or is this more about the formatting/style of the comment?

> I see a separate folder for map vars, put those variables in with other files by the use of the var. The files are small and separating them based on var type isn't very intuitive to me. I didn't know these existed until I started picking around

I agree, I'd like to see the maps & vars partial live in the same folder. 

> Convert extends into mixins since extends cannot be used in media queries and what we save on CSS parsing for having less rules is teensy weensy

Sure, there's only 5 anyway. Open a PR for those! :) 

> Include @see documentation for variables/mixins/functions that are closely tied to a specific variables/mixins/functions, e.g. pfe-breakpoint alludes to named breakpoints but doesn't describe them or provide a pointer to the var.

+1, I'd find this helpful too.

**Comment by wesruv** [comment]
Things from our meeting:
* Will using PF's colors mean we don't need to/should hold off on reworking their organization/usage? @starryeyez024 
* @wesruv  to implement SassDoc with @castastrophe 
* Look in style labeled issues to see if there are other Sass QOL issues we can do before 1.0

**Comment by wesruv** [comment]
Re: @starryeyez024:
> Have you looked at the /pfe-styles/_temp/pfe-colors.css file? This is a handy reference.
I didn't know that existed, I'd have to figure out how it mapped to Sass vars, which doesn't seem immediately obvious... from our meeting though I think implementing SassDoc would be a great opportunity to make colors clearest.

> Should we include the list, commented out, in our partials?
Hooooopefully Sassdoc can help us with that? If not I think that's the best idea I can think of...

> Can you elaborate on this? We have maps-a-plenty. Where are we specifically missing them?
At first I missed the colors map, and would normally expect that all colors were in a map, instead of a standalone var and a map. @castastrophe talked me through the evolution of that. I'd be in for helping move towards 'maps only' but the question above re:using PF's colors sounds like we need to work that out first.

> afaik they all have comment blocks above each. Are there some specifically that need more elaborate comments? Or is this more about the formatting/style of the comment?
Yes, I'm going to take a crack at documenting them in the Sassdoc PR and @ mention Cassondra and/or the author when I can't figure it out

**Comment by starryeyez024** [comment]
@wesruv I think we still should use PF core colors, regardless of how integrated the rest of the code may or may not be. It's one step that it will make it easier for all of us since we are still collaborating at the design level.

> > Have you looked at the /pfe-styles/_temp/pfe-colors.css file? This is a handy reference.

> I didn't know that existed, I'd have to figure out how it mapped to Sass vars, which doesn't seem immediately obvious... from our meeting though I think implementing SassDoc would be a great opportunity to make colors clearest.

I think the idea is that if you're building a component, you don't need to use sass vars 90% of the time. You use this file to look up a hex value and or a semantically named variable, like `  --theme--link--hover: #003366;`  and then in the component sass file, you use a function to fetch that color by name, `color: pfe-color(link--hover);`. The sass functions do all the magic for you, like printing all the right CSS vars and fallbacks.

> > Should we include the list, commented out, in our partials?

> Hooooopefully Sassdoc can help us with that? If not I think that's the best idea I can think of...

Maybe I take this one back, according to my answer above. The hex values in pfe-colors.css are still being populated by PF core, so you should be able to find what you're looking for there.

**Comment by wesruv** [comment]
I'm working on implementing SassDoc, it's going well but I noticed our whitespace in pfe-sass has white-space issues.

I'm seeing mixed tabs and spaces on lines
Some lines are 4 space tabs, some are 2

Looking at .editorconfig, every other file type is set to have 2 spaces, and if I look at different element's SCSS file they have 2 spaces (and no tabs).

I vote we add scss to this block of .editorconfig rules and update pfe-sass to have consistent spacing.
```
[*.{js,py,json,sh,html}]
indent_style = space
indent_size = 2
# No trailing spaces
trim_trailing_whitespace = true
# Unix-style newlines
end_of_line = lf
# Newline ending every file
insert_final_newline = true
```

**Comment by castastrophe** [comment]
Sounds good 👍 Alternatively, we could remove *.scss and *.css from prettierignore

**Comment by wesruv** [comment]
@mwcz mentioned that it wasn't working well when it was initially tried, probably want to investigate how well it works before implementing it.

I'm not opposed to trying it again to see if it improved
