### ISSUE TITLE
Replace ShaddyCss with CssVarPonyfill

### ISSUE THREAD

**Issue by grandemayta** [patternfly/patternfly-elements#953]
Hi guys,

we are using PatternFly Elements in our project, but we are facing into some issues with Css Variables and IE11. I understood that ShaddyCss has limited features. Is it possible to have a variant with [css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill)?

**Comment by castastrophe** [comment]
Hi @grandemayta!  Thank you so much for opening this issue.

Our IE11 fallbacks are fairly simplistic; in general, we don't expect the custom properties to work in IE11.  Our philosophy is graceful degradation but not 1:1 design fidelity.  You'll notice in several of the components we have styles wrapped in IE11 media queries that apply strong background and text styles.  A band component for example that might use a gray background in latest Chrome or Firefox will always have a white background in IE11.

On top of this, we've also included `postcss-custom-properties`, a plugin that I suspect is very similar to the polyfill you reference.  The way we are layering our variables for theming support however means that these polyfills only give us about 60% polyfill support because they can't traverse up and down our stylesheets to figure out what value we intended (on top of this, external themes are applied post-compile).

I hope that information and context is helpful.  We'd be happy to touch base with you more to learn about your use-case though and talk through this approach in more detail.
